export const ckEditorConfig = {
  // plugins: [CodeBlock],
  toolbar: {
    items: [
      "heading",
      "|",
      "fontSize",
      "fontFamily",
      "|",
      "bold",
      "italic",
      "underline",
      "strikethrough",
      "highlight",
      "|",
      "alignment",
      "|",
      "numberedList",
      "bulletedList",
      "|",
      "outdent",
      "indent",
      "|",
      "link",
      "imageUpload",
      "blockQuote",
      "CodeBlock",
      "|",
      "fontColor",
      "fontBackgroundColor",
      "|",
      "insertTable",
      "|",
      "undo",
      "redo",
    ],
    shouldNotGroupWhenFull: true,
  },
  language: "en",
  image: {
    toolbar: [
      "imageTextAlternative",
      "imageStyle:inline",
      "imageStyle:block",
      "imageStyle:side",
    ],
  },
  table: {
    contentToolbar: ["tableColumn", "tableRow", "mergeTableCells"],
  },
  licenseKey:
    "U3VMUU5kTmpaVzhSSEw5OVRyc0VPR1Q2bHdUWEE5WkYweXZDN1RmQWEwcURlYmRlWWNmemNpSXkzUmJsLU1qQXlOREF6TVRNPQ==",
};

export const formats = [
  "header",
  "height",
  "bold",
  "italic",
  "underline",
  "strike",
  "blockquote",
  "list",
  "color",
  "bullet",
  "indent",
  "link",
  "image",
  "align",
  "size",
];
